INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1000, 'Drama');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Romance');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Fantasy');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1000, 'Warner Bros Pictures');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Paramount');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1001, 'Normal People', 1000, 1000, 100, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1002, 'Pride And Prejudice', 1001, 1001, 50, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1003, 'Harry Potter and The Philosophers Stone', 1001, 1002, 30, CURRENT_TIMESTAMP);